
# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# The assistant project unique identifier
# This default value must be replaced with a unique assistant name within your deployment
assistant_id: 20240113-165019-weary-plaster

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
# language: en


language: "en"



pipeline:
# defines the sequence of components
  - name: WhitespaceTokenizer  # Splits the input text into tokens based on whitespace.
  #- name: LexicalSyntacticFeaturizer #Extracts features based on the lexical and syntactic properties of the input text.
  - name: CountVectorsFeaturizer # Converts the text into a bag-of-words representation by counting the occurrences of words.
  - name: CountVectorsFeaturizer
    analyzer: char_wb # helps in capturing character-level information within words while respecting word boundaries
    min_ngram: 1
    max_ngram: 4
  # - name: actions.custom_preprocessor.CustomPreprocessor
  - name: DIETClassifier # intent classification and entity recognition.
    epochs: 100 # trained for 100 epochs with constrain similarities
    constrain_similarities: true
  # - name: actions.custom_postprocessor.CustomPostprocessor
  - name: EntitySynonymMapper #Maps synonyms of entities to canonical forms.
  - name: ResponseSelector # Selects a predefined response for the assistant.
    learning_rate: 0.1
    epochs: 100
    constrain_similarities: true
  - name: FallbackClassifier # Handles fallback scenarios when confidence is less then threshold
    threshold: 0.5

policies:
#  how the assistant selects actions based on the current conversation state
  - name: MemoizationPolicy #Memorizes and predicts actions based on historical conversation patterns.
  - name: RulePolicy # Allows defining rules for mapping specific user inputs to actions
    core_fallback_threshold: 0.4
    core_fallback_action_name: "action_default_fallback"
    enable_fallback_prediction: True
  - name: UnexpecTEDIntentPolicy #Handles unexpected user intents that were not seen during training.
    max_history: 5
    epochs: 100
  - name: TEDPolicy # policy based on transformer architectures.
    max_history: 5
    epochs: 100
    constrain_similarities: true
