# # # The config recipe.
# # # https://rasa.com/docs/rasa/model-configuration/
# # recipe: default.v1

# # # The assistant project unique identifier
# # # This default value must be replaced with a unique assistant name within your deployment
# # assistant_id: 20240113-165019-weary-plaster

# # # # Configuration for Rasa NLU.
# # # # https://rasa.com/docs/rasa/nlu/components/
# # language: en

# # pipeline: 
# # # No configuration for the NLU pipeline was provided. The following default pipeline was used to train your model.
# # # If you'd like to customize it, uncomment and adjust the pipeline.
# # # See https://rasa.com/docs/rasa/tuning-your-model for more information.
# #   - name: LanguageModelTokenizer
# #   - name: LanguageModelFeaturizer
# #     model_name: bert-base-multilingual-uncased
# #   - name: SpacyNLP
# #     model: en_core_web_md
# #   # - name: SpacyTokenizer
#   # - name: WhitespaceTokenizer #Tokenizes the input based on whitespaces
# #   - name: SpacyFeaturizer
# #   - name: RegexFeaturizer
# #   - name: CRFEntityExtractor  #Uses Conditional Random Fields to extract entities
# #   - name: LexicalSyntacticFeaturizer
# #   - name: CountVectorsFeaturizer
# #   - name: CountVectorsFeaturizer
# #     analyzer: char_wb
# #     min_ngram: 1
# #     max_ngram: 4
# #   - name: DIETClassifier
# #     epochs: 100
# #     constrain_similarities: true
# #   - name: EntitySynonymMapper
# #   - name: ResponseSelector
# #     epochs: 100


# # # Configuration for Rasa Core.
# # # https://rasa.com/docs/rasa/core/policies/
# # policies:
# # # # No configuration for policies was provided. The following default policies were used to train your model.
# # # # If you'd like to customize them, uncomment and adjust the policies.
# # # # See https://rasa.com/docs/rasa/policies for more information.
# #   - name: MemoizationPolicy   #remembers the stories from stories.yml file
# #   - name: RulePolicy   #remenbres the rules from rules.yml file
# # #   - name: UnexpecTEDIntentPolicy
# # #     max_history: 5
# # #     epochs: 50
# # #   - name: TEDPolicy
# # #     max_history: 5  # how many conversational steps your assistant keeps in the memory when making the prediction
# #     epochs: 50
# #     constrain_similarities: true

# # language: en  # Default language is English

# # pipeline:
# #   - name: WhitespaceTokenizer #Tokenizes the input based on whitespaces
# #   - name: RegexFeaturizer #Extracts features from tokens using regular expressions.
# #   - name: CRFEntityExtractor  #Uses Conditional Random Fields to extract entities
# #   - name: EntitySynonymMapper #Resolves entity synonyms to improve recognition.
# #   - name: CountVectorsFeaturizer #Converts words into numerical vectors for intent classification.
# #     analyzer: char_wb
# #     min_ngram: 1
# #     max_ngram: 4
# #   # - name: EmbeddingIntentClassifier #Uses embeddings for intent classification
# #   #   intent_tokenization_flag: true
# #   #   intent_split_symbol: +
# #   # - name: DucklingHTTPExtractor # Extracts entities like time, number, and duration using Duckling.
# #   #   url: http://localhost:8000
# #   #   dimensions:
# #   #     - time
# #   #     - number
# #   #     - duration
# #   - name: SpacyNLP    #Uses spaCy for NLP tasks.
# #     model: en_core_web_md
# #   - name: SklearnIntentClassifier  #Provides an additional layer of intent classification using scikit-learn.
# #   # - name: DenseFeaturizer #responsible for converting text input into dense feature vectors that can be used by the intent classifier.
# #   # - name: FallbackClassifier 
# #   #   threshold: 0.3
# #   #   ambiguity_threshold: 0.1

# # policies:
# #   - name: MemoizationPolicy
# #   - name: TEDPolicy
# #   - name: RulePolicy
# # The config recipe.
# # https://rasa.com/docs/rasa/model-configuration/
# recipe: default.v1

# # The assistant project unique identifier
# # This default value must be replaced with a unique assistant name within your deployment
# assistant_id: 20240113-165019-weary-plaster

# # Configuration for Rasa NLU.
# # https://rasa.com/docs/rasa/nlu/components/
# language: en

# pipeline: 
# # # No configuration for the NLU pipeline was provided. The following default pipeline was used to train your model.
# # # If you'd like to customize it, uncomment and adjust the pipeline.
# # # See https://rasa.com/docs/rasa/tuning-your-model for more information.
#   - name: SpacyNLP
#     model: en_core_web_md
#   # - name: LanguageModelTokenizer
#   - name: WhitespaceTokenizer #Tokenizes the input based on whitespaces
#   - name: LanguageModelFeaturizer
#     model_name: bert-base-multilingual-uncased
#   - name: SklearnIntentClassifier
#   # - name: SpacyTokenizer
#   # - name: SpacyFeaturizer
#   # - name: RegexFeaturizer
#   - name: LexicalSyntacticFeaturizer
#   - name: CountVectorsFeaturizer
#   - name: CountVectorsFeaturizer
#     analyzer: "char_wb"
#     min_ngram: 1
#     max_ngram: 4
#   - name: DIETClassifier
#     epochs: 100
#     constrain_similarities: true
#   - name: EntitySynonymMapper
#   - name: ResponseSelector
#     epochs: 100


# # Configuration for Rasa Core.
# # https://rasa.com/docs/rasa/core/policies/
# policies:
# # # No configuration for policies was provided. The following default policies were used to train your model.
# # # If you'd like to customize them, uncomment and adjust the policies.
# # # See https://rasa.com/docs/rasa/policies for more information.
#   - name: MemoizationPolicy   #remembers the stories from stories.yml file
#   - name: RulePolicy   #remenbres the rules from rules.yml file
#   # - name: UnexpecTEDIntentPolicy
#   #   max_history: 5
#   #   epochs: 50
#   # - name: TEDPolicy
#   #   max_history: 5  # how many conversational steps your assistant keeps in the memory when making the prediction
#   #   epochs: 50
#   #   constrain_similarities: true
# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# The assistant project unique identifier
# This default value must be replaced with a unique assistant name within your deployment
assistant_id: 20240113-165019-weary-plaster

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en

pipeline: 
# # No configuration for the NLU pipeline was provided. The following default pipeline was used to train your model.
# # If you'd like to customize it, uncomment and adjust the pipeline.
# # See https://rasa.com/docs/rasa/tuning-your-model for more information.
  - name: SpacyNLP
    model: en_core_web_md
  - name: SpacyTokenizer
  - name: SpacyFeaturizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 50
    constrain_similarities: true
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100


# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
# # No configuration for policies was provided. The following default policies were used to train your model.
# # If you'd like to customize them, uncomment and adjust the policies.
# # See https://rasa.com/docs/rasa/policies for more information.
  - name: MemoizationPolicy   #remembers the stories from stories.yml file
  - name: RulePolicy   #remenbres the rules from rules.yml file
  # - name: UnexpecTEDIntentPolicy
  #   max_history: 5
  #   epochs: 50
  # - name: TEDPolicy
  #   max_history: 5  # how many conversational steps your assistant keeps in the memory when making the prediction
  #   epochs: 50
  #   constrain_similarities: true
